/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: dylanheyes (https://sketchfab.com/dylanheyes)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d
-models/minimalistic-modern-office-5540183da1c7452f810f8de33734879a
Title: Minimalistic Modern Office
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Room(props) {
  const { nodes, materials } = useGLTF('/models/minimalistic_modern_office.glb')

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 4]} scale={0.2}>
        <group rotation={[Math.PI / 2, 1, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, Math.PI / 2, 0]} scale={[310, 1130, 310]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Minimalistic_Modern_Office_Glass_0.geometry}
              material={materials.Glass}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Minimalistic_Modern_Office_Structure_0.geometry}
              material={materials.Structure}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Minimalistic_Modern_Office_Plants_0.geometry}
              material={materials.Plants}
            />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Minimalistic_Modern_Office_Plants_0_1.geometry}
                material={materials.Plants}
              />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Minimalistic_Modern_Office_Lights_0.geometry}
              material={materials.Lights}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Minimalistic_Modern_Office_LightEmission_0.geometry}
              material={materials.LightEmission}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Carpet_Carpet_0.geometry}
              material={materials.Carpet}
              position={[1.001, 0, 2.439]}
              rotation={[0, -Math.PI / 2, 0]}
              scale={[1.39, 0.463, 1.39]}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/minimalistic_modern_office.glb')


